name: dart_service_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/codelovercc/dart_service_provider

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
