name: dart_service_provider
description: An services dependency provider, like dependency inject, easy to learn and easy to use.
version: 1.0.5
repository: https://github.com/codelovercc/dart_service_provider

environment:
  sdk: ^3.6.0

dependencies:
  dart_logging_abstraction: ^1.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
